name: Deploy to Azure Web App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install all dependencies
        run: npm ci

      - name: Build
        run: npx webpack --mode production && mkdir -p dist/assets && cp -r src/assets/* dist/assets/

      - name: Install production dependencies only
        run: npm ci --omit=dev

      - name: List files before deploy
        run: ls -la && ls dist/

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'Nextage-dlp-app'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: '.'
